### ISSUE TITLE
read data from s3 and update to duckdb v1 

### ISSUE THREAD

**Issue by YuriyGavrilov** [hawkfish/duckdb-taco#8]
Hi @hawkfish thanks for make taco. it its very useful.

I tried to read data from s3 and it seams it not possible currently. 
I can't use SET in the create view so I can't making necessary configuration and load httpfs.

<img width="565" alt="Снимок экрана 2024-08-04 в 13 24 53" src="https://github.com/user-attachments/assets/29de041a-dea4-4070-b43a-f39ab6a01f25">

**Comment by hawkfish** [comment]
Mother Duck has taken over this project, and I suspect it does work, but you need to ask them.
